### PR TITLE
Removed vendor folder

### PR DESCRIPTION
**Pull request by wkhunt**

### CODE REVIEW

**Comment by chambbj** [comment]
I'd think that you would want to pull a release (or tag/branch) tarball as the source `url`, rather than use master.

**Comment by wkhunt** [comment]
I left it at master as none of the bfalg-ndwi tags actually work

**Comment by wkhunt** [comment]
And this solution is a very simple 'get it done' thing, it wont/cant transfer to other environments

**Comment by chambbj** [comment]
I'm clearly not in the loop on what is needed here, but I don't really understand "none of the bfalg-ndwi tags actually work." I also thought that this repo ended up feeding Nexus, which would impact deployments, no?

**Pull request closed without merging**
